# Generated by Django 3.0.6 on 2020-07-06 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='uname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='主机'),
        ),
        migrations.AddField(
            model_name='server',
            name='version',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='版本'),
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=32, verbose_name='容量')),
                ('slot', models.CharField(max_length=32, verbose_name='槽口')),
                ('model', models.CharField(max_length=32, verbose_name='模型')),
                ('speed', models.CharField(max_length=32, verbose_name='速率')),
                ('manufacturer', models.CharField(max_length=32, verbose_name='厂商')),
                ('sn', models.CharField(max_length=32, verbose_name='序列号')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server', verbose_name='服务器')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=32, verbose_name='厂商')),
                ('model', models.CharField(max_length=32, verbose_name='类型')),
                ('sn', models.CharField(max_length=32, verbose_name='序列号')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server', verbose_name='服务器')),
            ],
        ),
        migrations.CreateModel(
            name='AssetsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server', verbose_name='服务器')),
            ],
        ),
    ]
