# Generated by Django 3.0.6 on 2020-07-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200706_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='last_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近汇报时间'),
        ),
    ]
